### ISSUE TITLE
Please Support Savage RIFTS

### ISSUE THREAD

**Issue by voidstate** [jdgwf/savage-worlds-web-tools#65]
Is supporting Savage RIFTS a possibility?

Thanks

**Comment by jdgwf** [comment]
It's possible, but keeping up with all the frameworks and options is a huge mess. It'd take me a month of work.

Plus I'll have to ask permission from Palladium to use their copyrighted names.....

**Comment by schmendrick** [comment]
what about the general question: 

somebody requests setting XYZ or even better a pull request for setting XYZ: 

what is the answer? does it depend on the setting? does it depend if it comes from peginc directly, eg. is it a "yes" if it comes from peginc and a "no" for everything else?
does it depend if the guy giving you a pull request got the permission?

I ask because i consider to sit down and type the Interface Zero stuff by gun metal games down and include it to your tool, but if its legally not allowed and you therefore cannot take it, then that of course wouldnt make much sense... or maybe the basic hellfrost gear. 

i suggest you putting your answer into your readme, i am sure more people than me and voidstate wonder...

**Comment by jdgwf** [comment]
The answer is I have to have permission from the publishers to add any data. I won't be soliciting that until I feel the core is stable. :)
